"""Phase 6: end-to-end browser validation via Playwright.

Runs AFTER :class:`ReconciliationStage` has finished. The goal is to
catch the class of bugs that unit tests and static type-checking
structurally cannot catch:

- A Next.js page that compiles fine but crashes on hydration because
  a server-side import leaked into a client component.
- A FastAPI + frontend pair where the frontend fetches ``/api/users``
  but the backend wrote ``/api/user``.
- CORS / CSP misconfigurations that only manifest when a real browser
  tries to load the page.
- Route-level regressions (404s on nav, broken form submission) that
  unit tests don't exercise.

Implementation notes:

- This is a **single extended Claude Agent SDK invocation**, matching
  the reconciliation stage's approach. The SDK already handles the
  multi-turn detect → install → plan → write → run → report cycle
  we need.
- CWD is set to the run's output directory so the agent's Bash +
  Read/Write tools operate only on generated code for this run.
- The Docker image bundles Chromium, Firefox, and WebKit browser
  binaries at build time, so the agent does NOT need to run
  ``playwright install`` unless ``npx @playwright/test`` reports a
  missing browser (a graceful fallback path that only runs on the
  first invocation in a dev-mode image).
- **Best-effort**: any failure — agent crash, timeout, missing server
  start script, flaky test — is swallowed into an ``error`` or
  ``partial`` status. The pipeline always delivers the reconciled
  feature output; Phase 6 is polish, not gatekeeping.
- The stage writes ``E2E_REPORT.md`` at the root of the run's output
  directory with a human-readable summary, plus captures any
  Playwright HTML report and failure screenshots into
  ``e2e_artifacts/`` so the Run Detail popup can surface them.
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Any, Literal

import structlog
from pydantic import BaseModel, Field

from dark_factory.agents.cancellation import PipelineCancelled

log = structlog.get_logger()


_ALLOWED_BROWSERS = ("chromium", "firefox", "webkit")


# The prompt is deliberately structured as a 6-step checklist so the
# SDK's planning model can emit a clear TODO list at turn 0 and tick
# items off as it progresses. Mirrors the reconciliation prompt's
# structure for consistency.
_E2E_PROMPT_TEMPLATE = """\
You are a senior QA engineer running the final end-to-end browser
validation pass on code that was generated by a multi-feature agent
swarm and then cross-checked by a reconciliation pass. Your current
working directory is the ROOT of all generated output for this
pipeline run. The reconciliation pass reported status
``{reconciliation_status}`` — treat that as "the code compiles and
unit tests mostly pass; now make sure it actually WORKS in a real
browser."

Run ID: {run_id}
Features delivered this run ({feature_count}): {feature_list}
Browsers to test against: {browser_list}
Playwright browsers are pre-installed at: {browsers_path}

Your goal is to verify the generated application actually runs and
serves its core user flows across every browser in the matrix. Work
through these steps in order:

## 1. Detect
Use Glob + Read to determine whether this run produced a web
application. Any of these are strong signals:
- A ``package.json`` with a ``scripts.start`` or ``scripts.dev`` entry
- A ``Dockerfile`` that ``EXPOSE``s a port
- ``*.html`` entry point (``index.html``, ``public/index.html``)
- A known framework manifest (Next.js, Vite, Nuxt, Astro, SvelteKit)
- A FastAPI / Express / Flask server file with route definitions

If it is NOT a web app, stop. Write ``E2E_REPORT.md`` with
``Overall status: skipped`` and a one-line explanation of why no
browser tests were run (e.g. "pure Python library — no web UI
detected"). Do NOT try to invent a web app that isn't there.

## 2. Install
If the project does not already have ``@playwright/test`` in its
``package.json``, install it:

  npm install --save-dev @playwright/test

Playwright's browser binaries are ALREADY installed in this
container under ``{browsers_path}``. You do NOT need to run
``npx playwright install`` unless ``npx playwright test`` reports a
missing browser on first invocation.

## 3. Plan
Read the specs (look in ``../specs/`` or ``specs/`` or
``RECONCILIATION_REPORT.md``) and pick 3–8 user-facing acceptance
criteria that are reachable through the UI. Prefer:
- Page loads (home, login, dashboard, main entry point)
- Happy-path form submissions (login, signup, search)
- Navigation flows (click → new page → expected content)
- Critical data read paths (list pages, detail pages)

Ignore pure-backend acceptance criteria (database migrations,
background jobs, internal APIs not exposed to the UI).

## 4. Write
Create ``e2e/smoke.spec.ts`` (or ``.js`` if the project is plain
JavaScript) with one test per selected criterion. Keep them minimal:

  import {{ test, expect }} from '@playwright/test';

  test('home page loads', async ({{ page }}) => {{
    await page.goto('http://localhost:3000');
    await expect(page).toHaveTitle(/expected title/);
  }});

Also create a minimal ``playwright.config.ts`` that enables the
browser matrix {{ {browser_list} }}:

  import {{ defineConfig, devices }} from '@playwright/test';
  export default defineConfig({{
    testDir: './e2e',
    projects: [
{browser_projects}
    ],
    reporter: [['list'], ['html', {{ outputFolder: 'e2e_artifacts/html-report', open: 'never' }}]],
  }});

## 5. Run
Start the server in the background using whatever command the
project's ``package.json`` (or ``Dockerfile``, or README) indicates.
Pick a free port and export it as ``$PORT`` if the framework
respects it. Save the PID to a file and set a trap so the server is
killed on ANY exit path, including test failure:

  (npm run start > server.log 2>&1 & echo $! > .e2e-server.pid)
  trap 'kill "$(cat .e2e-server.pid)" 2>/dev/null || true' EXIT

Poll for server readiness before running tests. Detect the
health endpoint (prefer ``/health``, fall back to ``/``):

  curl --silent --retry 30 --retry-delay 1 --retry-connrefused \\
       --output /dev/null http://localhost:3000/

If readiness polling times out, record "server_startup_timeout" in
the report and stop — do not run tests against a dead server.

Run the full suite across all browsers:

  npx playwright test --reporter=line,html

Capture stdout + stderr. Parse the summary line for passed / failed
counts.

## 6. Report
Write ``E2E_REPORT.md`` at the ROOT of the working directory
containing:

- **Detection**: the signals you found that classified this as a
  web app, and the server start command you chose.
- **Browsers tested**: one line per browser in the matrix.
- **Test results**: a table with columns (test name, chromium,
  firefox, webkit, duration). Use ✓ / ✗ / — for status.
- **Failures**: for each failing test, include the failure reason
  and the screenshot path (if one was captured to
  ``e2e_artifacts/``).
- **Follow-ups**: anything you couldn't fully validate within the
  turn budget.
- **Overall status**: ONE of:
    - ``pass`` — every browser passed every test
    - ``partial`` — some failures but the app at least boots and
      most tests run to completion
    - ``broken`` — the app failed to start, the test suite failed
      to run, or every test failed

If you hit the turn budget before reaching step 5, write whatever
you have so far into the report and mark it ``partial``. A partial
report is infinitely more useful than a missing one.

Do NOT delete or disable failing tests to make them pass. If a test
is genuinely wrong (e.g. the spec changed), note the mismatch in
the report and leave the test in place.

Start now. Work through the steps methodically — do NOT skip the
detection or report phases.
"""


class E2EValidationResult(BaseModel):
    """Outcome of a Phase 6 end-to-end validation pass."""

    status: Literal["pass", "partial", "error", "skipped"]
    """``pass`` = every browser passed every test.
    ``partial`` = some failures or the agent stopped mid-checklist.
    ``error`` = agent crashed, timed out, or couldn't start.
    ``skipped`` = not a web app / reconciliation errored / disabled."""

    summary: str
    """One-line human-readable summary for the Run Detail popup."""

    tests_total: int = 0
    tests_passed: int = 0
    tests_failed: int = 0

    browsers_run: list[str] = Field(default_factory=list)
    """Browsers the agent actually exercised, parsed from the report
    when possible. May be a subset of the requested matrix if the
    agent hit the turn budget mid-run."""

    agent_output: str = ""
    """Deep agent final result text, capped at 8 KiB."""

    report_path: str | None = None
    """Path to ``E2E_REPORT.md`` relative to the run output
    directory, or ``None`` if the agent didn't produce one."""

    html_report_path: str | None = None
    """Path to the Playwright HTML report directory relative to the
    run output directory, or ``None``."""

    screenshots: list[str] = Field(default_factory=list)
    """Relative paths of any failure screenshots captured under
    ``e2e_artifacts/``. Surfaced in the Run Detail popup's Output
    screen as inline thumbnails."""

    duration_seconds: float = 0.0


class E2EValidationStage:
    """Runs the Playwright deep-agent pass on a completed run's output.

    Not a ``Stage`` subclass — operates on a filesystem path plus the
    reconciliation status, not on ``PipelineContext``. Kept
    intentionally small: all the heavy lifting happens inside the
    Claude Agent SDK invocation itself.
    """

    name = "e2e_validation"

    def __init__(
        self,
        *,
        max_turns: int = 40,
        timeout_seconds: int = 1200,
        browsers: list[str] | None = None,
        browsers_path: str = "/ms-playwright",
    ) -> None:
        self.max_turns = max(1, max_turns)
        self.timeout_seconds = max(60, timeout_seconds)
        # Filter to the allowed set so an operator typo in
        # ``e2e_browsers`` can't produce a malformed Playwright
        # config that fails the test run before it starts.
        self.browsers = [
            b for b in (browsers or list(_ALLOWED_BROWSERS)) if b in _ALLOWED_BROWSERS
        ] or list(_ALLOWED_BROWSERS)
        self.browsers_path = browsers_path

    def run(
        self,
        *,
        run_id: str,
        output_dir: Path,
        feature_results: list[dict[str, Any]],
        reconciliation_status: str,
    ) -> E2EValidationResult:
        """Execute the E2E validation pass.

        :param run_id: the pipeline run id (for logging / metrics only)
        :param output_dir: absolute path to the run's output root
        :param feature_results: ``completed_features`` from the
            orchestrator. Used only to populate the prompt's feature
            list for context — the agent derives its own plan from
            the specs on disk.
        :param reconciliation_status: the status returned by
            :class:`ReconciliationStage`. An ``error`` status causes
            this stage to skip entirely — there's no point running
            browser tests against code that couldn't even be cleaned
            up by reconciliation.
        """
        from dark_factory.agents.tools import emit_progress

        started = time.time()

        # ── Skip guards ─────────────────────────────────────────────
        if reconciliation_status == "error":
            log.info(
                "e2e_validation_skipped",
                reason="reconciliation_errored",
                run_id=run_id,
            )
            return E2EValidationResult(
                status="skipped",
                summary="Reconciliation errored — skipping E2E validation",
                duration_seconds=0.0,
            )

        if not feature_results:
            log.info(
                "e2e_validation_skipped",
                reason="no_features",
                run_id=run_id,
            )
            return E2EValidationResult(
                status="skipped",
                summary="No features to validate",
                duration_seconds=0.0,
            )

        if not output_dir.exists() or not output_dir.is_dir():
            log.warning(
                "e2e_validation_skipped",
                reason="output_dir_missing",
                run_id=run_id,
                output_dir=str(output_dir),
            )
            return E2EValidationResult(
                status="skipped",
                summary=f"Output dir {output_dir} missing",
                duration_seconds=0.0,
            )

        # ── Build the prompt ────────────────────────────────────────
        feature_names = [r.get("feature", "?") for r in feature_results]
        browser_list = ", ".join(self.browsers)
        # Playwright config projects block — indent 6 spaces to land
        # inside the `projects: [` array.
        browser_projects = ",\n".join(
            f"      {{ name: '{b}', use: {{ ...devices['Desktop {b.capitalize() if b != 'webkit' else 'Safari'}'] }} }}"
            for b in self.browsers
        )
        prompt = _E2E_PROMPT_TEMPLATE.format(
            run_id=run_id,
            feature_count=len(feature_results),
            feature_list=", ".join(feature_names) or "(none)",
            browser_list=browser_list,
            browser_projects=browser_projects,
            browsers_path=self.browsers_path,
            reconciliation_status=reconciliation_status,
        )

        # ── Announce the phase ──────────────────────────────────────
        emit_progress(
            "e2e_started",
            run_id=run_id,
            feature_count=len(feature_results),
            browsers=self.browsers,
            max_turns=self.max_turns,
            timeout_seconds=self.timeout_seconds,
        )
        log.info(
            "e2e_validation_starting",
            run_id=run_id,
            output_dir=str(output_dir),
            browsers=self.browsers,
            max_turns=self.max_turns,
        )

        # ── Run the deep agent ──────────────────────────────────────
        # Lazy import so test code can stub out ``_run_deep_agent``
        # without pulling the Claude Agent SDK at module import time.
        from dark_factory.agents import tools as _tools_mod

        # Swap ``_output_dir`` to the run output so the deep-agent
        # subprocess's cwd resolves there. Save + restore so we don't
        # leak into any subsequent pipeline work. Mirrors the
        # reconciliation stage's pattern.
        previous_output = _tools_mod._output_dir
        _tools_mod._output_dir = output_dir

        agent_output = ""
        agent_error: Exception | None = None
        try:
            agent_output = _tools_mod._run_deep_agent(
                prompt=prompt,
                allowed_tools=[
                    "Read",
                    "Write",
                    "Edit",
                    "Glob",
                    "Grep",
                    "Bash",
                ],
                max_turns=self.max_turns,
                timeout_seconds=float(self.timeout_seconds),
            )
        except PipelineCancelled:
            # B2 fix: cooperative cancel signal must propagate
            # through best-effort stages. Without this guard, a
            # Cancel click during Phase 6 E2E validation would get
            # swallowed by the broad ``except Exception`` below and
            # the pipeline would return a spurious success state.
            _tools_mod._output_dir = previous_output
            raise
        except Exception as exc:
            agent_error = exc
            log.error(
                "e2e_validation_failed",
                run_id=run_id,
                error=str(exc),
            )
        finally:
            _tools_mod._output_dir = previous_output

        duration = time.time() - started

        # ── Classify the outcome ────────────────────────────────────
        report_path: str | None = None
        report_abs = output_dir / "E2E_REPORT.md"
        report_text = ""
        if report_abs.exists():
            report_path = "E2E_REPORT.md"
            try:
                report_text = report_abs.read_text(errors="replace")
            except Exception:  # pragma: no cover — defensive
                report_text = ""

        # Playwright HTML report — conventionally written to
        # e2e_artifacts/html-report/ per the prompt's config block.
        html_report_path: str | None = None
        html_abs = output_dir / "e2e_artifacts" / "html-report"
        if html_abs.is_dir() and (html_abs / "index.html").exists():
            html_report_path = "e2e_artifacts/html-report"

        # Screenshot discovery — any .png files under e2e_artifacts/
        # at any depth. Playwright writes failure screenshots into a
        # test-specific subdirectory.
        screenshots: list[str] = []
        artifacts_dir = output_dir / "e2e_artifacts"
        if artifacts_dir.is_dir():
            for png in sorted(artifacts_dir.rglob("*.png")):
                try:
                    screenshots.append(
                        str(png.relative_to(output_dir))
                    )
                except ValueError:  # pragma: no cover — defensive
                    pass

        # Test counts + browsers-run are parsed opportunistically from
        # the agent's final message AND the report file concatenated
        # together. The prompt asks for specific shapes but we don't
        # enforce — if parsing fails we fall back to zeros and still
        # classify correctly from the status line.
        combined_text = f"{agent_output}\n{report_text}"
        tests_total, tests_passed, tests_failed = _parse_test_counts(combined_text)
        browsers_run = _parse_browsers_run(combined_text, self.browsers)

        if agent_error is not None:
            status: Literal["pass", "partial", "error", "skipped"] = "error"
            summary = f"E2E validation errored: {agent_error}"
        elif not agent_output and not report_text:
            status = "error"
            summary = "E2E validation produced no output"
        else:
            haystack = f"{agent_output}\n{report_text}".lower()
            if "overall status: skipped" in haystack or "overall status:skipped" in haystack:
                status = "skipped"
                summary = "E2E validation skipped — not a web application"
            elif (
                "overall status: pass" in haystack
                or "overall status:pass" in haystack
                or "status: pass" in haystack
            ):
                status = "pass"
                summary = (
                    f"E2E validation passed across {len(browsers_run) or len(self.browsers)} browser(s)"
                )
            elif (
                "overall status: broken" in haystack
                or "overall status:broken" in haystack
            ):
                status = "partial"
                summary = "E2E validation broken — significant runtime failures"
            else:
                status = "partial"
                summary = "E2E validation finished with some failures or gaps"

        emit_progress(
            "e2e_completed",
            run_id=run_id,
            status=status,
            summary=summary,
            duration_seconds=duration,
            tests_total=tests_total,
            tests_passed=tests_passed,
            tests_failed=tests_failed,
            browsers_run=browsers_run,
            report_path=report_path,
        )
        log.info(
            "e2e_validation_complete",
            run_id=run_id,
            status=status,
            duration_seconds=round(duration, 1),
            report_path=report_path,
            tests_total=tests_total,
            tests_passed=tests_passed,
            tests_failed=tests_failed,
        )

        return E2EValidationResult(
            status=status,
            summary=summary,
            tests_total=tests_total,
            tests_passed=tests_passed,
            tests_failed=tests_failed,
            browsers_run=browsers_run,
            agent_output=agent_output[:8000],  # cap for incident storage
            report_path=report_path,
            html_report_path=html_report_path,
            screenshots=screenshots,
            duration_seconds=duration,
        )


# ── Report parsing helpers ───────────────────────────────────────────────────


def _parse_test_counts(report_text: str) -> tuple[int, int, int]:
    """Extract (total, passed, failed) from the E2E report.

    Looks for explicit ``N passed`` / ``N failed`` / ``N total``
    markers in Playwright's output or in the markdown report. Returns
    zeros if nothing parseable is found — the status classification
    falls back to string matching on the overall status line.
    """
    if not report_text:
        return (0, 0, 0)
    import re

    passed = 0
    failed = 0
    # "12 passed" or "12 passing" etc.
    m = re.search(r"(\d+)\s+pass(?:ed|ing)", report_text, re.IGNORECASE)
    if m:
        passed = int(m.group(1))
    m = re.search(r"(\d+)\s+fail(?:ed|ing)", report_text, re.IGNORECASE)
    if m:
        failed = int(m.group(1))
    total = passed + failed
    # Prefer an explicit total if present (handles skipped tests).
    m = re.search(r"(\d+)\s+total", report_text, re.IGNORECASE)
    if m:
        total = int(m.group(1))
    return (total, passed, failed)


def _parse_browsers_run(report_text: str, default: list[str]) -> list[str]:
    """Look for browser names mentioned in the report.

    Returns only browsers from the requested matrix that appear in
    the text, preserving the requested order. If none are found, we
    fall back to the full requested matrix (we conservatively assume
    every browser was attempted).
    """
    if not report_text:
        return list(default)
    text = report_text.lower()
    found = [b for b in default if b in text]
    return found or list(default)
